I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/ltf_act_2/scene_10_imFeelingLucky.rpy", line 42, in script
    saki "{i}Out of the hospital.{/i}"
Exception: Sayer 'saki' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/ltf_act_2/scene_10_imFeelingLucky.rpy", line 42, in script
    saki "{i}Out of the hospital.{/i}"
  File "E:\renpy-8.0.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "E:\renpy-8.0.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\renpy-8.0.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'saki' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Katawa Shoujo Stories Beyond 1.0
Tue Sep  3 22:20:56 2024
