I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/ltf_act_1/scene_1_detour.rpy", line 101, in script
    Saki "Excuse me..."
NameError: name 'saki_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/ltf_act_1/scene_1_detour.rpy", line 101, in script
    Saki "Excuse me..."
  File "E:\renpy-8.0.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "E:\renpy-8.0.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\renpy-8.0.3-sdk\renpy\exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "E:\renpy-8.0.3-sdk\renpy\character.py", line 1374, in __call__
    who = renpy.python.py_eval(who)
  File "E:\renpy-8.0.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\renpy-8.0.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'saki_name' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Katawa Shoujo Stories Beyond 1.0
Thu Aug  8 21:58:25 2024
